export class GraphFraudEngine {
    constructor() {
        // Directed graph representation: adjacency list
        this.adjList = new Map();
        // Stores transaction history overall
        this.transactions = [];
        // Tracks account metadata (e.g., last active, risk scores)
        this.accounts = new Map();
    }

    _initAccount(id) {
        if (!this.adjList.has(id)) {
            this.adjList.set(id, []);
            this.accounts.set(id, {
                id,
                firstActive: Date.now(),
                lastActive: 0, // 0 for newly discovered
                riskScore: 0,
                flags: []
            });
        }
    }

    addTransaction(tx) {
        // tx: { id, from, to, amount, timestamp } // id generated by backend
        this._initAccount(tx.from);
        this._initAccount(tx.to);

        const sender = this.accounts.get(tx.from);
        
        // Dormant account logic: > 30 days of inactivity and high value
        const thirtyDaysMs = 30 * 24 * 60 * 60 * 1000;
        if (sender.lastActive > 0 && (tx.timestamp - sender.lastActive) > thirtyDaysMs && tx.amount > 100000) {
            sender.flags.push({ type: 'DORMANT_ACTIVATION', details: 'Inactive account suddenly transferred large amount', txId: tx.id });
        }

        sender.lastActive = tx.timestamp;
        this.accounts.get(tx.to).lastActive = tx.timestamp;

        this.adjList.get(tx.from).push(tx);
        this.transactions.push(tx);

        return this.analyzeTransaction(tx);
    }

    // Trigger specific checks on a new transaction
    analyzeTransaction(tx) {
        let frauds = [];

        // 1. Loop Detection
        if (this.detectLoop(tx.from)) {
            frauds.push({ type: 'LOOP_DETECTED', details: 'Circular transaction path detected', accountsInvolved: [tx.from] });
            this.accounts.get(tx.from).flags.push({ type: 'LOOP_DETECTED', rxId: tx.id });
        }

        // 2. Rapid Transfer Chains
        if (this.detectRapidTransfer(tx.from, tx.to, tx.timestamp)) {
            frauds.push({ type: 'RAPID_TRANSFER_CHAIN', details: 'Multi-hop transfer within short time window', accountsInvolved: [tx.from, tx.to] });
            this.accounts.get(tx.from).flags.push({ type: 'RAPID_TRANSFER_CHAIN', rxId: tx.id });
        }

        // 3. Smurfing
        if (this.detectSmurfing(tx.from, tx.timestamp)) {
            frauds.push({ type: 'SMURFING', details: 'Many small transfers to multiple recipients', accountsInvolved: [tx.from] });
            this.accounts.get(tx.from).flags.push({ type: 'SMURFING', rxId: tx.id });
        }

        this.updateScores();
        return frauds;
    }

    detectLoop(startNode, maxDepth = 4) {
        // DFS looking for startNode within maxDepth
        let visited = new Set();
        let foundLoop = false;

        const dfs = (currNode, depth) => {
            if (depth > maxDepth) return;
            if (depth > 0 && currNode === startNode) {
                foundLoop = true;
                return;
            }
            if (visited.has(currNode)) return;
            visited.add(currNode);

            let neighbors = this.adjList.get(currNode) || [];
            for (let edge of neighbors) {
                dfs(edge.to, depth + 1);
                if (foundLoop) return;
            }
            visited.delete(currNode); // Backtrack
        };

        dfs(startNode, 0);
        return foundLoop;
    }

    detectRapidTransfer(from, to, time) {
        // Check if "from" received funds very recently (from somewhere else), and is now sending them out
        let receivedEdges = this.transactions.filter(t => t.to === from && (time - t.timestamp) < 300000); // 5 minutes
        return receivedEdges.length > 0;
    }

    detectSmurfing(from, time) {
        // Check if "from" sent >= 3 small transactions to different accounts in the last hour
        let outgoing = this.transactions.filter(t => t.from === from && (time - t.timestamp) < 3600000 && t.amount < 10000); // 1 hour, < 10k amount
        
        let uniqueRecipients = new Set(outgoing.map(t => t.to));
        return uniqueRecipients.size >= 3;
    }

    updateScores() {
        for (let [id, acc] of this.accounts.entries()) {
            let score = 0;
            // Base score off of flags
            let flagCounts = {
                LOOP: acc.flags.filter(f => f.type === 'LOOP_DETECTED').length,
                RAPID: acc.flags.filter(f => f.type === 'RAPID_TRANSFER_CHAIN').length,
                SMURF: acc.flags.filter(f => f.type === 'SMURFING').length,
                DORMANT: acc.flags.filter(f => f.type === 'DORMANT_ACTIVATION').length
            };

            score += flagCounts.LOOP * 30;
            score += flagCounts.RAPID * 25;
            score += flagCounts.SMURF * 20;
            score += flagCounts.DORMANT * 40;

            acc.riskScore = Math.min(100, Math.max(0, score));
        }
    }

    getAccountAnalysis(id) {
        const acc = this.accounts.get(id);
        if (!acc) return null;

        let riskCategory = 'LOW';
        if (acc.riskScore >= 70) riskCategory = 'HIGH';
        else if (acc.riskScore >= 40) riskCategory = 'MEDIUM';

        // Connected accounts
        let connected = new Set();
        (this.adjList.get(id) || []).forEach(tx => connected.add(tx.to));
        this.transactions.filter(t => t.to === id).forEach(tx => connected.add(tx.from));

        return {
            id: acc.id,
            transactionHistory: this.transactions.filter(t => t.from === id || t.to === id),
            connectedAccounts: Array.from(connected),
            riskScore: acc.riskScore,
            riskCategory,
            fraudReasons: acc.flags,
            timestamp: new Date().toISOString()
        };
    }

    getFullAnalysis() {
        let loops = [];
        let rapid = [];
        let smurfing = [];
        let dormant = [];
        let accountScores = {};

        for (let [id, acc] of this.accounts.entries()) {
            acc.flags.forEach(f => {
                if (f.type === 'LOOP_DETECTED') loops.push(id);
                if (f.type === 'RAPID_TRANSFER_CHAIN') rapid.push(id);
                if (f.type === 'SMURFING') smurfing.push(id);
                if (f.type === 'DORMANT_ACTIVATION') dormant.push(id);
            });

            accountScores[id] = {
                score: acc.riskScore,
                category: acc.riskScore >= 70 ? 'HIGH' : (acc.riskScore >= 40 ? 'MEDIUM' : 'LOW')
            };
        }

        // Deduplicate
        return {
            loopsDetected: [...new Set(loops)],
            rapidTransferChains: [...new Set(rapid)],
            smurfingAccounts: [...new Set(smurfing)],
            dormantAccountAlerts: [...new Set(dormant)],
            accountScores,
            generatedAt: new Date().toISOString()
        };
    }
}
